---
name: Mopidy base image

on:
  push:
    paths:
      - 'Dockerfile-base'

jobs:
  docker-mopidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker mopidy-base
        run: make build-docker-mopidy
      - name: Push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: cristianpb/mopidy-base
          tags: latest
          target: base
          dockerfile: Dockerfile-base
