---
name: Mopidy base image

on:
  push:
    paths:
      - 'Dockerfile-base'

jobs:
  docker-mopidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-base
          push: true
          build-args: arg1=value1,arg2=value2
          tags: cristianpb/mopidy-base:latest
          target: base
