---
name: Build html & Publish to github pages

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - '**'         # Push events on all branchs
    tags:        
      - v*           # Push events with tags starting with v

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install node requirements
        run: npm ci
      - name: build html
        run: |
          npm run export
      - name: deploy to github pages
        if: success() && steps.extract_branch.outputs.branch == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./__sapper__/export/apollo
      - name: Build python package
        run: |
          export APP_VERSION=$(git describe --tags )
          sed -i -E "s/version = (.*)/version = ${APP_VERSION:1}/"  setup.cfg
          cp  -r ./__sapper__/export/apollo mopidy_apollo/static
          python3 -m pip install  --upgrade setuptools wheel
          python3 setup.py sdist bdist_wheel
      - name: Publish package 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        if: startsWith(github.event.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
      - name: Create Release
        if: startsWith(github.event.ref, 'refs/tags')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        if: startsWith(github.event.ref, 'refs/tags')
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Mopidy-Apollo-*.tar.gz
          asset_name: Mopidy-Apollo.tar.gz
          asset_content_type: application/tar+gzip
